language: node_js
notifications:
  email:
    recipients:
      - sir.serje@gmail.com
    on_success: always # default: change
before_install:
    - rm -rf package-lock.json
    - "npm install -g yarn"